In [7]:
import torch

In [8]:
torch.__version__

'1.13.1+cu116'

# create tensors

In [10]:
scalar = torch.tensor(5)

In [11]:
scalar

tensor(5)

In [12]:
scalar.ndim()

0

In [13]:
scalar.item()

5

In [ ]:
house = ['bed','bath','kitech']

In [17]:
# vector
vec = torch.tensor([4,5])

In [18]:
# check dim
vec.ndim

1

In [19]:
# check shape
vec.shape


torch.Size([2])

In [20]:
# matrix
Mat = torch.tensor([[1,2]
                    ,[7,9]])

In [21]:
Mat

tensor([[1, 2],
        [7, 9]])

In [22]:
# check the number of dimensions

In [24]:
Mat.ndim

2

In [25]:
Mat.shape

torch.Size([2, 2])

In [27]:
# tenor
ten = torch.tensor([[[1,2,3],
                     [4,5,9],
                     [4,5,9]]])

In [28]:
ten

tensor([[[1, 2, 3],
         [4, 5, 9],
         [4, 5, 9]]])

In [29]:
ten.ndim

3

In [30]:
ten.shape

torch.Size([1, 3, 3])

In [31]:
# random tenors

In [34]:
random_tensor = torch.rand(size=(3,4))
print(random_tensor)
print(random_tensor.dtype)

tensor([[0.0964, 0.3888, 0.2587, 0.9230],
        [0.7701, 0.3502, 0.5407, 0.4602],
        [0.0179, 0.2705, 0.3794, 0.9265]])
torch.float32


In [35]:
random_image_tensor = torch.rand(size=(224,224,3))

In [36]:
random_image_tensor

tensor([[[8.8030e-01, 3.3937e-01, 9.6080e-01],
         [6.7301e-03, 9.3145e-01, 4.1837e-01],
         [3.0145e-01, 6.1627e-01, 7.2769e-02],
         ...,
         [2.8165e-01, 8.6830e-01, 1.6256e-01],
         [4.5802e-02, 4.2508e-01, 3.4557e-01],
         [5.0914e-01, 7.6703e-01, 5.0445e-01]],

        [[4.1228e-01, 1.9492e-01, 2.1644e-02],
         [3.2344e-01, 9.2078e-01, 3.2926e-01],
         [1.7675e-01, 5.6827e-01, 6.5515e-01],
         ...,
         [4.9069e-01, 2.3594e-01, 9.3456e-01],
         [5.4790e-01, 9.8169e-01, 2.4574e-02],
         [7.8192e-01, 5.4830e-01, 4.6061e-02]],

        [[4.5708e-01, 9.3848e-01, 5.0621e-01],
         [2.2147e-01, 5.2443e-02, 3.7075e-01],
         [2.6707e-01, 1.7150e-01, 1.4393e-01],
         ...,
         [8.1029e-01, 4.3724e-01, 9.2870e-01],
         [7.0251e-01, 2.3247e-01, 6.4098e-02],
         [9.1350e-01, 6.5994e-04, 9.9648e-01]],

        ...,

        [[3.9143e-01, 8.8460e-02, 3.2694e-01],
         [5.0978e-01, 6.6066e-01, 8.1010e-01]

In [37]:
random_image_tensor.shape,random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [38]:
zero=torch.zeros(size=(4,3))

In [40]:
zero,zero.ndim

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]), 2)

In [41]:
zero.dtype

torch.float32

In [42]:
one = torch.ones(size=(3,3))
one,one.dtype,one.ndim

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), torch.float32, 2)

In [45]:
# create values from 0 to 12
zero_to_twilv =torch.range(start=0,end=12,step=1)

<ipython-input-45-010713fd8009>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_twilv =torch.range(start=0,end=12,step=1)


In [47]:
zero_to_twilv
zero_to_twilv.dtype

torch.float32