In [1]:
# here for importing our packages
import torch
import numpy as np

In [2]:
torch.cuda.is_available()

False

In [44]:
# create array
data = [[4,5],[6,7]]
data

[[4, 5], [6, 7]]

In [45]:
type(data)

list

In [47]:
np.array(data)

array([[4, 5],
       [6, 7]])

In [6]:
np.asarray(data)

array([[4, 5],
       [6, 7]])

In [48]:
tr=torch.tensor(data)

In [49]:
type(tr)

torch.Tensor

In [50]:
tr.dtype

torch.int64

In [10]:
# numpy array
num_arr = np.random.rand(3,4)
num_arr

array([[0.91679023, 0.85463621, 0.20261278, 0.53919522],
       [0.94388496, 0.49338134, 0.11484042, 0.67167014],
       [0.61884623, 0.89378593, 0.18758151, 0.76681308]])

In [11]:
# convert to torch
torch.from_numpy(num_arr)

tensor([[0.9168, 0.8546, 0.2026, 0.5392],
        [0.9439, 0.4934, 0.1148, 0.6717],
        [0.6188, 0.8938, 0.1876, 0.7668]], dtype=torch.float64)

In [12]:
torch.tensor(num_arr)

tensor([[0.9168, 0.8546, 0.2026, 0.5392],
        [0.9439, 0.4934, 0.1148, 0.6717],
        [0.6188, 0.8938, 0.1876, 0.7668]], dtype=torch.float64)

In [13]:
torch.ones(4,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.zeros(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
# genrate random
first_ten=torch.rand(4,5)

In [16]:
first_ten.dtype

torch.float32

In [17]:
first_ten.device

device(type='cpu')

In [18]:
first_ten

tensor([[0.8521, 0.1487, 0.3250, 0.2491, 0.3121],
        [0.4461, 0.3481, 0.9816, 0.3503, 0.5237],
        [0.0864, 0.6395, 0.1116, 0.9721, 0.7437],
        [0.0306, 0.2760, 0.3799, 0.1468, 0.3317]])

In [19]:
first_ten[:,1:3]

tensor([[0.1487, 0.3250],
        [0.3481, 0.9816],
        [0.6395, 0.1116],
        [0.2760, 0.3799]])

In [20]:
# multiplication
first_ten.mul(first_ten)

tensor([[7.2603e-01, 2.2112e-02, 1.0560e-01, 6.2030e-02, 9.7414e-02],
        [1.9902e-01, 1.2120e-01, 9.6347e-01, 1.2268e-01, 2.7431e-01],
        [7.4578e-03, 4.0893e-01, 1.2459e-02, 9.4489e-01, 5.5304e-01],
        [9.3411e-04, 7.6187e-02, 1.4430e-01, 2.1556e-02, 1.1004e-01]])

In [21]:
first_ten * first_ten

tensor([[7.2603e-01, 2.2112e-02, 1.0560e-01, 6.2030e-02, 9.7414e-02],
        [1.9902e-01, 1.2120e-01, 9.6347e-01, 1.2268e-01, 2.7431e-01],
        [7.4578e-03, 4.0893e-01, 1.2459e-02, 9.4489e-01, 5.5304e-01],
        [9.3411e-04, 7.6187e-02, 1.4430e-01, 2.1556e-02, 1.1004e-01]])

In [22]:
first_ten.matmul(first_ten.T)

tensor([[1.0132, 1.0016, 0.6792, 0.3306],
        [1.0016, 1.6807, 1.1007, 0.7078],
        [0.6792, 1.1007, 1.9268, 0.6110],
        [0.3306, 0.7078, 0.6110, 0.3530]])

In [23]:
torch.matmul(first_ten,first_ten.T)

tensor([[1.0132, 1.0016, 0.6792, 0.3306],
        [1.0016, 1.6807, 1.1007, 0.7078],
        [0.6792, 1.1007, 1.9268, 0.6110],
        [0.3306, 0.7078, 0.6110, 0.3530]])

In [24]:
first_ten @ first_ten.T

tensor([[1.0132, 1.0016, 0.6792, 0.3306],
        [1.0016, 1.6807, 1.1007, 0.7078],
        [0.6792, 1.1007, 1.9268, 0.6110],
        [0.3306, 0.7078, 0.6110, 0.3530]])

In [26]:
# sum of all elements
first_ten.sum(axis=1)

tensor([1.8869, 2.6498, 2.5532, 1.1650])

In [27]:
first_ten.sum()

tensor(8.2549)

In [51]:
# concatination can use axis and dim
torch.concat([first_ten,first_ten])

tensor([[0.8521, 0.1487, 0.3250, 0.2491, 0.3121],
        [0.4461, 0.3481, 0.9816, 0.3503, 0.5237],
        [0.0864, 0.6395, 0.1116, 0.9721, 0.7437],
        [0.0306, 0.2760, 0.3799, 0.1468, 0.3317],
        [0.8521, 0.1487, 0.3250, 0.2491, 0.3121],
        [0.4461, 0.3481, 0.9816, 0.3503, 0.5237],
        [0.0864, 0.6395, 0.1116, 0.9721, 0.7437],
        [0.0306, 0.2760, 0.3799, 0.1468, 0.3317]])

In [36]:
torch.nn.functional.softmax(first_ten,dim=0)

tensor([[0.3889, 0.2004, 0.2087, 0.1972, 0.2085],
        [0.2592, 0.2446, 0.4023, 0.2182, 0.2577],
        [0.1809, 0.3274, 0.1686, 0.4064, 0.3211],
        [0.1710, 0.2276, 0.2204, 0.1781, 0.2127]])

In [37]:
torch.nn.functional.softmax(first_ten,dim=1)

tensor([[0.3110, 0.1539, 0.1836, 0.1702, 0.1813],
        [0.1784, 0.1618, 0.3048, 0.1621, 0.1928],
        [0.1232, 0.2142, 0.1263, 0.2987, 0.2377],
        [0.1620, 0.2071, 0.2298, 0.1820, 0.2190]])

In [52]:
# we can check the size or the shap
print(first_ten.size())
print(first_ten.shape)

torch.Size([4, 5])
torch.Size([4, 5])


In [42]:
# example of image
torch.rand(10,3,128,128)

tensor([[[[0.6359, 0.3093, 0.8903,  ..., 0.3182, 0.6165, 0.9785],
          [0.7853, 0.8003, 0.5992,  ..., 0.3818, 0.2710, 0.4374],
          [0.3626, 0.2768, 0.8083,  ..., 0.2061, 0.5902, 0.5735],
          ...,
          [0.4535, 0.2132, 0.0679,  ..., 0.0188, 0.7023, 0.7373],
          [0.3475, 0.7915, 0.0981,  ..., 0.1249, 0.2483, 0.4405],
          [0.0789, 0.9570, 0.8585,  ..., 0.6310, 0.8748, 0.2042]],

         [[0.3890, 0.8960, 0.5225,  ..., 0.1455, 0.6686, 0.1122],
          [0.1508, 0.2708, 0.3272,  ..., 0.4602, 0.8775, 0.7937],
          [0.9829, 0.2501, 0.5699,  ..., 0.0338, 0.8746, 0.8851],
          ...,
          [0.9909, 0.3006, 0.0099,  ..., 0.4103, 0.9067, 0.7688],
          [0.9097, 0.0239, 0.2515,  ..., 0.1101, 0.9621, 0.2428],
          [0.7309, 0.1638, 0.3657,  ..., 0.5043, 0.5136, 0.2287]],

         [[0.3180, 0.5994, 0.3802,  ..., 0.6880, 0.8840, 0.7776],
          [0.0747, 0.1027, 0.1788,  ..., 0.5111, 0.0185, 0.1295],
          [0.0686, 0.4436, 0.2212,  ..., 0

In [43]:
# clip every thing

first_ten.clip(0.2,0.8)

tensor([[0.8000, 0.2000, 0.3250, 0.2491, 0.3121],
        [0.4461, 0.3481, 0.8000, 0.3503, 0.5237],
        [0.2000, 0.6395, 0.2000, 0.8000, 0.7437],
        [0.2000, 0.2760, 0.3799, 0.2000, 0.3317]])