In [1]:
import torch 

In [2]:
one_to_twinty = torch.range(start=1,end=20,step=1)

<ipython-input-2-f5cb598167ba>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_twinty = torch.range(start=1,end=20,step=1)


In [3]:
one_to_twinty

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20.])

In [6]:
one_to_twinty.shape

torch.Size([20])

In [4]:
zero_num = torch.zeros_like(input=one_to_twinty)

In [5]:
zero_num

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
zero_num.shape

torch.Size([20])

 # torch datatype

In [8]:
float_32 = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)

In [9]:
float_32

tensor([3., 6., 9.])

In [10]:
float_32.shape

torch.Size([3])

In [11]:
float_32.dtype

torch.float32

In [12]:
float_32.device

device(type='cpu')

In [13]:
# we can change the datatype

In [14]:
float_16 = torch.tensor([3.0,6.0,9.0],dtype=torch.float16)

In [15]:
float_16.dtype

torch.float16

In [16]:
float_16.device

device(type='cpu')

In [18]:
# create tensor
tensor = torch.rand(size=(3,4))
print(tensor)
print(f'the shape of tensor is:{tensor.shape}')
print(f' the datatype of ou tensor is:{tensor.dtype}')
print(f'our tensor storerd in :{tensor.device}')

tensor([[0.3333, 0.0829, 0.0954, 0.1700],
        [0.2094, 0.2321, 0.7745, 0.2836],
        [0.4139, 0.5310, 0.3674, 0.7724]])
the shape of tensor is:torch.Size([3, 4])
 the datatype of ou tensor is:torch.float32
our tensor storerd in :cpu


# operations in tenseros

In [19]:
# basic operations

tensor = torch.tensor([3,5,9])
tensor + 10 

tensor([13, 15, 19])

In [20]:
# multiply with 10 
tensor * 10

tensor([30, 50, 90])

In [21]:
# substract
tensor  - 12 

tensor([-9, -7, -3])

In [23]:
tensor = tensor + 10 
tensor

tensor([23, 25, 29])

In [24]:
tensor = tensor - 10 
tensor

tensor([13, 15, 19])

In [25]:
# we can also use torch functions$
torch.multiply(tensor,12)

tensor([156, 180, 228])

In [26]:
torch.add(tensor,14)

tensor([27, 29, 33])

In [28]:
print(tensor,"*",tensor)
print('Equal:',tensor*tensor)

tensor([13, 15, 19]) * tensor([13, 15, 19])
Equal: tensor([169, 225, 361])


In [29]:
tensor = torch.tensor([1,2,3])

In [30]:
print(tensor,'*',tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [31]:
tensor * tensor

tensor([1, 4, 9])

In [32]:
torch.matmul(tensor,tensor)

tensor(14)

In [35]:
tensor @ tensor

tensor(14)