pytorch  & numpy

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


# pytroch & numpy

In [16]:
import numpy as np
import torch 

In [17]:
array = np.arange(1.0,12.0)
tensor = torch.from_numpy(array)
array,tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        dtype=torch.float64))

In [19]:
tensor1 = torch.from_numpy(array).type(torch.float32)

torch.Tensor

In [20]:
# let change numpy and see if torch can changed or not
array = array + 1 
tensor,array

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
        dtype=torch.float64),
 array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [21]:
# change tensor to numpy
tensor = torch.ones(10)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [22]:
tensor = tensor + 1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [25]:
# crreate two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(f'random_tensor_a:\n{random_tensor_a}\n')
print(f'random_tensor_b:\n{random_tensor_b}\n')

print('random_tensor_a and random_tensor_b equal?')
random_tensor_a == random_tensor_b

random_tensor_a:
tensor([[0.5315, 0.1587, 0.6542, 0.3278],
        [0.6532, 0.3958, 0.9147, 0.2036],
        [0.2018, 0.2018, 0.9497, 0.6666]])

random_tensor_b:
tensor([[0.9811, 0.0874, 0.0041, 0.1088],
        [0.1637, 0.7025, 0.6790, 0.9155],
        [0.2418, 0.1591, 0.7653, 0.2979]])

random_tensor_a and random_tensor_b equal?


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
# create other tensor with random seed
import random
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(f'random_tensor_c:\n{random_tensor_c}\n')
print(f'random_tensor_d:\n{random_tensor_d}\n')

print('random_tensor_c and random_tensor_d equal?')
random_tensor_c == random_tensor_d


random_tensor_c:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

random_tensor_d:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

random_tensor_c and random_tensor_d equal?


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [29]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>