In [30]:
import torch

In [32]:
# create tensor
x = torch.arange(0,400,10)
x

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390])

In [33]:
x.ndim

1

In [34]:
# let's perform some aggreation
print(f'Minuimn:{x.min()}')
print(f'Maximum:{x.max()}')

Minuimn:0
Maximum:390


In [36]:
print(f'Mean:{x.type(torch.float32).mean()}')

Mean:195.0


In [37]:
print(f'Sum:{x.sum()}')

Sum:7800


# positional min/max

In [38]:
# create tensor
tensor = torch.arange(20,150,10)
tensor

tensor([ 20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140])

In [39]:
# reutrn of the index of min and max
print(f'index of max value :{tensor.argmax()}')
print(f'index of min value:{tensor.argmin()}')

index of max value :12
index of min value:0


In [40]:
# create tensor of float32
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [43]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [44]:
# create tensor int8
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [45]:
# create tensor 
x = torch.arange(1.,8.)
x.shape

torch.Size([7])

In [46]:
x_reshaped = x.reshape(1,7)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [47]:
x_reshaped.shape

torch.Size([1, 7])

In [49]:
# view method
e = x.view(1,7)
e

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [50]:
# chnaging e change x
e[:,0]=3

In [55]:
e

tensor([[3., 2., 3., 4., 5., 6., 7.]])

In [56]:
x

tensor([3., 2., 3., 4., 5., 6., 7.])

In [57]:
# stack tensor
x_stack = torch.stack([x,x,x,x],dim=0)
x_stack

tensor([[3., 2., 3., 4., 5., 6., 7.],
        [3., 2., 3., 4., 5., 6., 7.],
        [3., 2., 3., 4., 5., 6., 7.],
        [3., 2., 3., 4., 5., 6., 7.]])

In [59]:
x_stack = torch.stack([x,x,x,x],dim=1)
x_stack

tensor([[3., 3., 3., 3.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [61]:
x_reshaped


tensor([[3., 2., 3., 4., 5., 6., 7.]])

In [66]:
print(f'preivous tensor:{x_reshaped}')
print(f'preivous shape:{x_reshaped.shape} ')
print(f'ndim:{x_reshaped.ndim}')

preivous tensor:tensor([[3., 2., 3., 4., 5., 6., 7.]])
preivous shape:torch.Size([1, 7]) 
ndim:2


In [65]:
x_squeeze = x_reshaped.squeeze()
print(f'New\n tensor:{x_squeeze}')
print(f'New\n shape:{x_squeeze.shape}')
print(f'new ndim:{x_squeeze.ndim}')

New
 tensor:tensor([3., 2., 3., 4., 5., 6., 7.])
New
 shape:torch.Size([7])
new ndim:1


In [67]:
x_squeeze = x_reshaped.squeeze()
print(f'New\n tensor:{x_squeeze}')
# add extra dim
x_unsqueeze = x_squeeze.unsqueeze(dim=0)
print(f'New\n shape:{x_unsqueeze.shape}')
print(f'new ndim:{x_unsqueeze.ndim}')

New
 tensor:tensor([3., 2., 3., 4., 5., 6., 7.])
New
 shape:torch.Size([1, 7])
new ndim:2


In [69]:
# permutation
a = torch.arange(1,10).reshape(3,3)
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [71]:
b = a.permute(1,0)
b

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [72]:
# create tensor with some dim
x_original = torch.rand(size=(224,224,3))
x_original

tensor([[[0.8726, 0.0718, 0.5808],
         [0.1651, 0.1532, 0.4581],
         [0.7041, 0.1055, 0.0575],
         ...,
         [0.9708, 0.0027, 0.6006],
         [0.1245, 0.0634, 0.1478],
         [0.4722, 0.3631, 0.4802]],

        [[0.3398, 0.5565, 0.8336],
         [0.2233, 0.0064, 0.1286],
         [0.3168, 0.6086, 0.7529],
         ...,
         [0.7243, 0.1061, 0.2714],
         [0.0026, 0.5992, 0.9962],
         [0.2603, 0.3408, 0.9763]],

        [[0.8135, 0.0856, 0.6361],
         [0.0565, 0.1166, 0.5323],
         [0.5189, 0.9074, 0.1996],
         ...,
         [0.7472, 0.4942, 0.6674],
         [0.7417, 0.8892, 0.5513],
         [0.4172, 0.7654, 0.7974]],

        ...,

        [[0.7402, 0.3578, 0.3785],
         [0.5108, 0.0271, 0.1531],
         [0.4872, 0.8285, 0.1490],
         ...,
         [0.4133, 0.4380, 0.3970],
         [0.8268, 0.2797, 0.6066],
         [0.6505, 0.9155, 0.2636]],

        [[0.0616, 0.1188, 0.0392],
         [0.8687, 0.9906, 0.3883],
         [0.

In [73]:
x_original.ndim

3

In [76]:
x_peru = x_original.permute(2,0,1)

In [77]:
print(f'preivous shape:{x_original.shape}')
print(f'New shape:{x_peru.shape}')

preivous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])
